# Generated by Django 6.0.1 on 2026-01-24 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_temperature', models.FloatField()),
                ('model_alpha', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=255)),
                ('sid', models.CharField(max_length=255)),
                ('stage', models.IntegerField(default=0)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.session')),
            ],
        ),
    ]
