# Generated by Django 6.0.1 on 2026-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='model',
        ),
        migrations.RemoveField(
            model_name='session',
            name='model_alpha',
        ),
        migrations.RemoveField(
            model_name='session',
            name='model_temperature',
        ),
        migrations.AddField(
            model_name='session',
            name='configs',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
