# Generated by Django 6.0.1 on 2026-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=255)),
                ('requester_sid', models.CharField(max_length=255)),
                ('is_responded', models.BooleanField(default=False)),
            ],
        ),
    ]
