# Generated by Django 6.0.1 on 2026-04-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkStateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_sid', models.CharField(max_length=255)),
                ('is_responded', models.BooleanField(default=False)),
                ('state_ids', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
