# Generated by Django 6.0.1 on 2026-04-13 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_sharing', '0002_bulkstaterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkstaterequest',
            old_name='state_ids',
            new_name='states',
        ),
        migrations.AlterField(
            model_name='bulkstaterequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('70c84491-271a-4fdb-8b11-37b96fdcc68e'), primary_key=True, serialize=False),
        ),
    ]
