# Generated by Django 6.0.1 on 2026-04-13 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_sharing', '0003_rename_state_ids_bulkstaterequest_states_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkstaterequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
